services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./src/main/resources/db/data/init.sql:/docker-entrypoint-initdb.d/init.sql
  cache:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning