CREATE TABLE book
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255)                                        NOT NULL,
    description      TEXT,
    publication_date DATE                                                NOT NULL,
    writting_date    DATE                                                NOT NULL,
    setting_literary_type_id BIGINT NOT NULL,
    author_id        BIGINT         NOT NULL,
    FOREIGN KEY (setting_literary_type_id) REFERENCES setting_literary_type (id),
    FOREIGN KEY (author_id) REFERENCES author (id)
);

CREATE INDEX idx_book_setting_literary_type_id ON book (setting_literary_type_id);
CREATE INDEX idx_book_author_id ON book (author_id);